# 配置端口号
server:
  port: 8080

# 数据库配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis-plus?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: rsq200106
  kafka:
    # Kafka连接地址
    bootstrap-servers: 39.107.40.71:9092
    # 生产者相关配置
    producer:
      retries: 3 # 客户端重新发送失败记录的次数
      batch-size: 16384
      buffer-memory: 33554432
      acks: 1
      # 指定消息key和消息体的编解码方式
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    # 消费者相关配置
    consumer:
      group-id: default-group
      enable-auto-commit: false
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      ack-mode: manual_immediate



# MyBatis-Plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 默认的控制台输出SQL日志
    map-underscore-to-camel-case: true # 开启驼峰自动命名识别
  # 全局配置逻辑删除
  global-config:
    db-config:
      logic-delete-field: deleted # 逻辑删除属性
      logic-delete-value: 1       # 逻辑已删除的值
      logic-not-delete-value: 0   # 逻辑未删除的值
  # mapper.xml文件所在的位置
  mapper-locations:
    - classpath*:dao/*.xml
    - classpath*:com/**/mapper/*.xml
  # 可以直接扫描的实体类
  type-aliases-package: com.shaoqiang.entity

